// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client_sdk} from '../models';
import {storage} from '../models';

export function CreateTag(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DownloadAttachment(arg1:string,arg2:string):Promise<string>;

export function ExportIdentity():Promise<string>;

export function GetChannelConfig(arg1:string,arg2:string):Promise<string>;

export function GetChannelMembers(arg1:string):Promise<Array<client_sdk.Member>>;

export function GetGridStats():Promise<Record<string, number>>;

export function GetHistory(arg1:string):Promise<Array<storage.Message>>;

export function GetJoinedChannels():Promise<Array<string>>;

export function GetMessageTags(arg1:string):Promise<Record<string, Array<storage.MessageTag>>>;

export function GetNodeID():Promise<string>;

export function GetRecentChats():Promise<Array<storage.ChatItem>>;

export function GetRole():Promise<string>;

export function GetTags(arg1:string):Promise<Array<storage.ChannelTag>>;

export function GetWikiPages(arg1:string):Promise<Array<storage.WikiPage>>;

export function Initialize(arg1:string):Promise<string>;

export function JoinChannel(arg1:string):Promise<string>;

export function KickUser(arg1:string,arg2:string):Promise<string>;

export function PromoteUser(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveWikiPage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendFile(arg1:string,arg2:string):Promise<string>;

export function SendMessage(arg1:string,arg2:string):Promise<string>;

export function SetChannelConfig(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartDM(arg1:string):Promise<string>;

export function TagMessage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UpdateChannelAvatar(arg1:string,arg2:string):Promise<string>;
