// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2, arg3);
}

export function DownloadAttachment(arg1, arg2) {
  return window['go']['main']['App']['DownloadAttachment'](arg1, arg2);
}

export function ExportIdentity() {
  return window['go']['main']['App']['ExportIdentity']();
}

export function GetChannelConfig(arg1, arg2) {
  return window['go']['main']['App']['GetChannelConfig'](arg1, arg2);
}

export function GetChannelMembers(arg1) {
  return window['go']['main']['App']['GetChannelMembers'](arg1);
}

export function GetGridStats() {
  return window['go']['main']['App']['GetGridStats']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetJoinedChannels() {
  return window['go']['main']['App']['GetJoinedChannels']();
}

export function GetMessageTags(arg1) {
  return window['go']['main']['App']['GetMessageTags'](arg1);
}

export function GetNodeID() {
  return window['go']['main']['App']['GetNodeID']();
}

export function GetRecentChats() {
  return window['go']['main']['App']['GetRecentChats']();
}

export function GetRole() {
  return window['go']['main']['App']['GetRole']();
}

export function GetTags(arg1) {
  return window['go']['main']['App']['GetTags'](arg1);
}

export function GetWikiPages(arg1) {
  return window['go']['main']['App']['GetWikiPages'](arg1);
}

export function Initialize(arg1) {
  return window['go']['main']['App']['Initialize'](arg1);
}

export function JoinChannel(arg1) {
  return window['go']['main']['App']['JoinChannel'](arg1);
}

export function KickUser(arg1, arg2) {
  return window['go']['main']['App']['KickUser'](arg1, arg2);
}

export function PromoteUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['PromoteUser'](arg1, arg2, arg3);
}

export function SaveWikiPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWikiPage'](arg1, arg2, arg3);
}

export function SendFile(arg1, arg2) {
  return window['go']['main']['App']['SendFile'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetChannelConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetChannelConfig'](arg1, arg2, arg3);
}

export function StartDM(arg1) {
  return window['go']['main']['App']['StartDM'](arg1);
}

export function TagMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['TagMessage'](arg1, arg2, arg3);
}

export function UpdateChannelAvatar(arg1, arg2) {
  return window['go']['main']['App']['UpdateChannelAvatar'](arg1, arg2);
}
