// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: admin.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNetworkStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkStatsRequest) Reset() {
	*x = GetNetworkStatsRequest{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkStatsRequest) ProtoMessage() {}

func (x *GetNetworkStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkStatsRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkStatsRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

type GetNetworkStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalNodes    int32                  `protobuf:"varint,1,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	OnlineNodes   int32                  `protobuf:"varint,2,opt,name=online_nodes,json=onlineNodes,proto3" json:"online_nodes,omitempty"`
	TotalUsers    int32                  `protobuf:"varint,3,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	TotalChannels int32                  `protobuf:"varint,4,opt,name=total_channels,json=totalChannels,proto3" json:"total_channels,omitempty"`
	TotalMessages int32                  `protobuf:"varint,5,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	NodesByType   map[string]int32       `protobuf:"bytes,6,rep,name=nodes_by_type,json=nodesByType,proto3" json:"nodes_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkStatsResponse) Reset() {
	*x = GetNetworkStatsResponse{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkStatsResponse) ProtoMessage() {}

func (x *GetNetworkStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkStatsResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkStatsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetNetworkStatsResponse) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *GetNetworkStatsResponse) GetOnlineNodes() int32 {
	if x != nil {
		return x.OnlineNodes
	}
	return 0
}

func (x *GetNetworkStatsResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetNetworkStatsResponse) GetTotalChannels() int32 {
	if x != nil {
		return x.TotalChannels
	}
	return 0
}

func (x *GetNetworkStatsResponse) GetTotalMessages() int32 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *GetNetworkStatsResponse) GetNodesByType() map[string]int32 {
	if x != nil {
		return x.NodesByType
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterType    NodeType               `protobuf:"varint,1,opt,name=filter_type,json=filterType,proto3,enum=network.v1.NodeType" json:"filter_type,omitempty"`
	OnlineOnly    bool                   `protobuf:"varint,2,opt,name=online_only,json=onlineOnly,proto3" json:"online_only,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListNodesRequest) GetFilterType() NodeType {
	if x != nil {
		return x.FilterType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *ListNodesRequest) GetOnlineOnly() bool {
	if x != nil {
		return x.OnlineOnly
	}
	return false
}

func (x *ListNodesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListNodesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnlineOnly    bool                   `protobuf:"varint,1,opt,name=online_only,json=onlineOnly,proto3" json:"online_only,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersRequest) GetOnlineOnly() bool {
	if x != nil {
		return x.OnlineOnly
	}
	return false
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserSummary         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersResponse) GetUsers() []*UserSummary {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UserSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	IsOnline      bool                   `protobuf:"varint,5,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *UserSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSummary) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSummary) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserSummary) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserSummary) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

type UpdateUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewRole       string                 `protobuf:"bytes,2,opt,name=new_role,json=newRole,proto3" json:"new_role,omitempty"` // "member", "admin", "owner"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRoleRequest) Reset() {
	*x = UpdateUserRoleRequest{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRoleRequest) ProtoMessage() {}

func (x *UpdateUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRoleRequest) GetNewRole() string {
	if x != nil {
		return x.NewRole
	}
	return ""
}

type UpdateUserRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRoleResponse) Reset() {
	*x = UpdateUserRoleResponse{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRoleResponse) ProtoMessage() {}

func (x *UpdateUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BanNodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // 0 = permanente
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BanNodeRequest) Reset() {
	*x = BanNodeRequest{}
	mi := &file_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanNodeRequest) ProtoMessage() {}

func (x *BanNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanNodeRequest.ProtoReflect.Descriptor instead.
func (*BanNodeRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{9}
}

func (x *BanNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BanNodeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BanNodeRequest) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type BanNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanNodeResponse) Reset() {
	*x = BanNodeResponse{}
	mi := &file_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanNodeResponse) ProtoMessage() {}

func (x *BanNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanNodeResponse.ProtoReflect.Descriptor instead.
func (*BanNodeResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{10}
}

func (x *BanNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BanNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnbanNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanNodeRequest) Reset() {
	*x = UnbanNodeRequest{}
	mi := &file_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanNodeRequest) ProtoMessage() {}

func (x *UnbanNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanNodeRequest.ProtoReflect.Descriptor instead.
func (*UnbanNodeRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{11}
}

func (x *UnbanNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UnbanNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanNodeResponse) Reset() {
	*x = UnbanNodeResponse{}
	mi := &file_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanNodeResponse) ProtoMessage() {}

func (x *UnbanNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanNodeResponse.ProtoReflect.Descriptor instead.
func (*UnbanNodeResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{12}
}

func (x *UnbanNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnbanNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendGlobalAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // "info", "warning", "critical"
	InfoUrl       string                 `protobuf:"bytes,4,opt,name=info_url,json=infoUrl,proto3" json:"info_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGlobalAlertRequest) Reset() {
	*x = SendGlobalAlertRequest{}
	mi := &file_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGlobalAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGlobalAlertRequest) ProtoMessage() {}

func (x *SendGlobalAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGlobalAlertRequest.ProtoReflect.Descriptor instead.
func (*SendGlobalAlertRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{13}
}

func (x *SendGlobalAlertRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendGlobalAlertRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendGlobalAlertRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *SendGlobalAlertRequest) GetInfoUrl() string {
	if x != nil {
		return x.InfoUrl
	}
	return ""
}

type SendGlobalAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGlobalAlertResponse) Reset() {
	*x = SendGlobalAlertResponse{}
	mi := &file_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGlobalAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGlobalAlertResponse) ProtoMessage() {}

func (x *SendGlobalAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGlobalAlertResponse.ProtoReflect.Descriptor instead.
func (*SendGlobalAlertResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{14}
}

func (x *SendGlobalAlertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendGlobalAlertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendGlobalAlertResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type VerifyMasterKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterKey     string                 `protobuf:"bytes,1,opt,name=master_key,json=masterKey,proto3" json:"master_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyMasterKeyRequest) Reset() {
	*x = VerifyMasterKeyRequest{}
	mi := &file_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMasterKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMasterKeyRequest) ProtoMessage() {}

func (x *VerifyMasterKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMasterKeyRequest.ProtoReflect.Descriptor instead.
func (*VerifyMasterKeyRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{15}
}

func (x *VerifyMasterKeyRequest) GetMasterKey() string {
	if x != nil {
		return x.MasterKey
	}
	return ""
}

type VerifyMasterKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VaultToken    string                 `protobuf:"bytes,3,opt,name=vault_token,json=vaultToken,proto3" json:"vault_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyMasterKeyResponse) Reset() {
	*x = VerifyMasterKeyResponse{}
	mi := &file_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMasterKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMasterKeyResponse) ProtoMessage() {}

func (x *VerifyMasterKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMasterKeyResponse.ProtoReflect.Descriptor instead.
func (*VerifyMasterKeyResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{16}
}

func (x *VerifyMasterKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyMasterKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyMasterKeyResponse) GetVaultToken() string {
	if x != nil {
		return x.VaultToken
	}
	return ""
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\n" +
	"network.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rnetwork.proto\"\x18\n" +
	"\x16GetNetworkStatsRequest\"\xe6\x02\n" +
	"\x17GetNetworkStatsResponse\x12\x1f\n" +
	"\vtotal_nodes\x18\x01 \x01(\x05R\n" +
	"totalNodes\x12!\n" +
	"\fonline_nodes\x18\x02 \x01(\x05R\vonlineNodes\x12\x1f\n" +
	"\vtotal_users\x18\x03 \x01(\x05R\n" +
	"totalUsers\x12%\n" +
	"\x0etotal_channels\x18\x04 \x01(\x05R\rtotalChannels\x12%\n" +
	"\x0etotal_messages\x18\x05 \x01(\x05R\rtotalMessages\x12X\n" +
	"\rnodes_by_type\x18\x06 \x03(\v24.network.v1.GetNetworkStatsResponse.NodesByTypeEntryR\vnodesByType\x1a>\n" +
	"\x10NodesByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x98\x01\n" +
	"\x10ListNodesRequest\x125\n" +
	"\vfilter_type\x18\x01 \x01(\x0e2\x14.network.v1.NodeTypeR\n" +
	"filterType\x12\x1f\n" +
	"\vonline_only\x18\x02 \x01(\bR\n" +
	"onlineOnly\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"`\n" +
	"\x11ListNodesResponse\x12*\n" +
	"\x05nodes\x18\x01 \x03(\v2\x14.network.v1.NodeInfoR\x05nodes\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"a\n" +
	"\x10ListUsersRequest\x12\x1f\n" +
	"\vonline_only\x18\x01 \x01(\bR\n" +
	"onlineOnly\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"c\n" +
	"\x11ListUsersResponse\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.network.v1.UserSummaryR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x80\x01\n" +
	"\vUserSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1b\n" +
	"\tis_online\x18\x05 \x01(\bR\bisOnline\"K\n" +
	"\x15UpdateUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bnew_role\x18\x02 \x01(\tR\anewRole\"L\n" +
	"\x16UpdateUserRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"l\n" +
	"\x0eBanNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x03R\x0fdurationSeconds\"E\n" +
	"\x0fBanNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\x10UnbanNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"G\n" +
	"\x11UnbanNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x7f\n" +
	"\x16SendGlobalAlertRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x19\n" +
	"\binfo_url\x18\x04 \x01(\tR\ainfoUrl\"h\n" +
	"\x17SendGlobalAlertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\"7\n" +
	"\x16VerifyMasterKeyRequest\x12\x1d\n" +
	"\n" +
	"master_key\x18\x01 \x01(\tR\tmasterKey\"n\n" +
	"\x17VerifyMasterKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vvault_token\x18\x03 \x01(\tR\n" +
	"vaultToken2\x9d\x05\n" +
	"\fAdminService\x12Z\n" +
	"\x0fGetNetworkStats\x12\".network.v1.GetNetworkStatsRequest\x1a#.network.v1.GetNetworkStatsResponse\x12H\n" +
	"\tListNodes\x12\x1c.network.v1.ListNodesRequest\x1a\x1d.network.v1.ListNodesResponse\x12H\n" +
	"\tListUsers\x12\x1c.network.v1.ListUsersRequest\x1a\x1d.network.v1.ListUsersResponse\x12W\n" +
	"\x0eUpdateUserRole\x12!.network.v1.UpdateUserRoleRequest\x1a\".network.v1.UpdateUserRoleResponse\x12B\n" +
	"\aBanNode\x12\x1a.network.v1.BanNodeRequest\x1a\x1b.network.v1.BanNodeResponse\x12H\n" +
	"\tUnbanNode\x12\x1c.network.v1.UnbanNodeRequest\x1a\x1d.network.v1.UnbanNodeResponse\x12Z\n" +
	"\x0fSendGlobalAlert\x12\".network.v1.SendGlobalAlertRequest\x1a#.network.v1.SendGlobalAlertResponse\x12Z\n" +
	"\x0fVerifyMasterKey\x12\".network.v1.VerifyMasterKeyRequest\x1a#.network.v1.VerifyMasterKeyResponseB3Z1github.com/goautomatik/core-server/pkg/pb/v1;pbv1b\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_admin_proto_goTypes = []any{
	(*GetNetworkStatsRequest)(nil),  // 0: network.v1.GetNetworkStatsRequest
	(*GetNetworkStatsResponse)(nil), // 1: network.v1.GetNetworkStatsResponse
	(*ListNodesRequest)(nil),        // 2: network.v1.ListNodesRequest
	(*ListNodesResponse)(nil),       // 3: network.v1.ListNodesResponse
	(*ListUsersRequest)(nil),        // 4: network.v1.ListUsersRequest
	(*ListUsersResponse)(nil),       // 5: network.v1.ListUsersResponse
	(*UserSummary)(nil),             // 6: network.v1.UserSummary
	(*UpdateUserRoleRequest)(nil),   // 7: network.v1.UpdateUserRoleRequest
	(*UpdateUserRoleResponse)(nil),  // 8: network.v1.UpdateUserRoleResponse
	(*BanNodeRequest)(nil),          // 9: network.v1.BanNodeRequest
	(*BanNodeResponse)(nil),         // 10: network.v1.BanNodeResponse
	(*UnbanNodeRequest)(nil),        // 11: network.v1.UnbanNodeRequest
	(*UnbanNodeResponse)(nil),       // 12: network.v1.UnbanNodeResponse
	(*SendGlobalAlertRequest)(nil),  // 13: network.v1.SendGlobalAlertRequest
	(*SendGlobalAlertResponse)(nil), // 14: network.v1.SendGlobalAlertResponse
	(*VerifyMasterKeyRequest)(nil),  // 15: network.v1.VerifyMasterKeyRequest
	(*VerifyMasterKeyResponse)(nil), // 16: network.v1.VerifyMasterKeyResponse
	nil,                             // 17: network.v1.GetNetworkStatsResponse.NodesByTypeEntry
	(NodeType)(0),                   // 18: network.v1.NodeType
	(*NodeInfo)(nil),                // 19: network.v1.NodeInfo
}
var file_admin_proto_depIdxs = []int32{
	17, // 0: network.v1.GetNetworkStatsResponse.nodes_by_type:type_name -> network.v1.GetNetworkStatsResponse.NodesByTypeEntry
	18, // 1: network.v1.ListNodesRequest.filter_type:type_name -> network.v1.NodeType
	19, // 2: network.v1.ListNodesResponse.nodes:type_name -> network.v1.NodeInfo
	6,  // 3: network.v1.ListUsersResponse.users:type_name -> network.v1.UserSummary
	0,  // 4: network.v1.AdminService.GetNetworkStats:input_type -> network.v1.GetNetworkStatsRequest
	2,  // 5: network.v1.AdminService.ListNodes:input_type -> network.v1.ListNodesRequest
	4,  // 6: network.v1.AdminService.ListUsers:input_type -> network.v1.ListUsersRequest
	7,  // 7: network.v1.AdminService.UpdateUserRole:input_type -> network.v1.UpdateUserRoleRequest
	9,  // 8: network.v1.AdminService.BanNode:input_type -> network.v1.BanNodeRequest
	11, // 9: network.v1.AdminService.UnbanNode:input_type -> network.v1.UnbanNodeRequest
	13, // 10: network.v1.AdminService.SendGlobalAlert:input_type -> network.v1.SendGlobalAlertRequest
	15, // 11: network.v1.AdminService.VerifyMasterKey:input_type -> network.v1.VerifyMasterKeyRequest
	1,  // 12: network.v1.AdminService.GetNetworkStats:output_type -> network.v1.GetNetworkStatsResponse
	3,  // 13: network.v1.AdminService.ListNodes:output_type -> network.v1.ListNodesResponse
	5,  // 14: network.v1.AdminService.ListUsers:output_type -> network.v1.ListUsersResponse
	8,  // 15: network.v1.AdminService.UpdateUserRole:output_type -> network.v1.UpdateUserRoleResponse
	10, // 16: network.v1.AdminService.BanNode:output_type -> network.v1.BanNodeResponse
	12, // 17: network.v1.AdminService.UnbanNode:output_type -> network.v1.UnbanNodeResponse
	14, // 18: network.v1.AdminService.SendGlobalAlert:output_type -> network.v1.SendGlobalAlertResponse
	16, // 19: network.v1.AdminService.VerifyMasterKey:output_type -> network.v1.VerifyMasterKeyResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	file_network_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
