// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: admin.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_GetNetworkStats_FullMethodName = "/network.v1.AdminService/GetNetworkStats"
	AdminService_ListNodes_FullMethodName       = "/network.v1.AdminService/ListNodes"
	AdminService_ListUsers_FullMethodName       = "/network.v1.AdminService/ListUsers"
	AdminService_UpdateUserRole_FullMethodName  = "/network.v1.AdminService/UpdateUserRole"
	AdminService_BanNode_FullMethodName         = "/network.v1.AdminService/BanNode"
	AdminService_UnbanNode_FullMethodName       = "/network.v1.AdminService/UnbanNode"
	AdminService_SendGlobalAlert_FullMethodName = "/network.v1.AdminService/SendGlobalAlert"
	AdminService_VerifyMasterKey_FullMethodName = "/network.v1.AdminService/VerifyMasterKey"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	// Retorna estatísticas globais da rede
	GetNetworkStats(ctx context.Context, in *GetNetworkStatsRequest, opts ...grpc.CallOption) (*GetNetworkStatsResponse, error)
	// Lista todos os nós registrados na rede
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// Lista usuários registrados ou online
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	// Alterar a role de um usuário (ex: promover a admin)
	UpdateUserRole(ctx context.Context, in *UpdateUserRoleRequest, opts ...grpc.CallOption) (*UpdateUserRoleResponse, error)
	// Banir um nó permanentemente ou temporariamente
	BanNode(ctx context.Context, in *BanNodeRequest, opts ...grpc.CallOption) (*BanNodeResponse, error)
	// Remover o banimento de um nó
	UnbanNode(ctx context.Context, in *UnbanNodeRequest, opts ...grpc.CallOption) (*UnbanNodeResponse, error)
	// Enviar um alerta/mensagem global para todos os clientes conectados
	SendGlobalAlert(ctx context.Context, in *SendGlobalAlertRequest, opts ...grpc.CallOption) (*SendGlobalAlertResponse, error)
	// Verifica a Chave Mestra para desbloqueio de ações críticas (Vault)
	VerifyMasterKey(ctx context.Context, in *VerifyMasterKeyRequest, opts ...grpc.CallOption) (*VerifyMasterKeyResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetNetworkStats(ctx context.Context, in *GetNetworkStatsRequest, opts ...grpc.CallOption) (*GetNetworkStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkStatsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetNetworkStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, AdminService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateUserRole(ctx context.Context, in *UpdateUserRoleRequest, opts ...grpc.CallOption) (*UpdateUserRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserRoleResponse)
	err := c.cc.Invoke(ctx, AdminService_UpdateUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) BanNode(ctx context.Context, in *BanNodeRequest, opts ...grpc.CallOption) (*BanNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BanNodeResponse)
	err := c.cc.Invoke(ctx, AdminService_BanNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UnbanNode(ctx context.Context, in *UnbanNodeRequest, opts ...grpc.CallOption) (*UnbanNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbanNodeResponse)
	err := c.cc.Invoke(ctx, AdminService_UnbanNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SendGlobalAlert(ctx context.Context, in *SendGlobalAlertRequest, opts ...grpc.CallOption) (*SendGlobalAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendGlobalAlertResponse)
	err := c.cc.Invoke(ctx, AdminService_SendGlobalAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) VerifyMasterKey(ctx context.Context, in *VerifyMasterKeyRequest, opts ...grpc.CallOption) (*VerifyMasterKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyMasterKeyResponse)
	err := c.cc.Invoke(ctx, AdminService_VerifyMasterKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	// Retorna estatísticas globais da rede
	GetNetworkStats(context.Context, *GetNetworkStatsRequest) (*GetNetworkStatsResponse, error)
	// Lista todos os nós registrados na rede
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// Lista usuários registrados ou online
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	// Alterar a role de um usuário (ex: promover a admin)
	UpdateUserRole(context.Context, *UpdateUserRoleRequest) (*UpdateUserRoleResponse, error)
	// Banir um nó permanentemente ou temporariamente
	BanNode(context.Context, *BanNodeRequest) (*BanNodeResponse, error)
	// Remover o banimento de um nó
	UnbanNode(context.Context, *UnbanNodeRequest) (*UnbanNodeResponse, error)
	// Enviar um alerta/mensagem global para todos os clientes conectados
	SendGlobalAlert(context.Context, *SendGlobalAlertRequest) (*SendGlobalAlertResponse, error)
	// Verifica a Chave Mestra para desbloqueio de ações críticas (Vault)
	VerifyMasterKey(context.Context, *VerifyMasterKeyRequest) (*VerifyMasterKeyResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetNetworkStats(context.Context, *GetNetworkStatsRequest) (*GetNetworkStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkStats not implemented")
}
func (UnimplementedAdminServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedAdminServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedAdminServiceServer) UpdateUserRole(context.Context, *UpdateUserRoleRequest) (*UpdateUserRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserRole not implemented")
}
func (UnimplementedAdminServiceServer) BanNode(context.Context, *BanNodeRequest) (*BanNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BanNode not implemented")
}
func (UnimplementedAdminServiceServer) UnbanNode(context.Context, *UnbanNodeRequest) (*UnbanNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbanNode not implemented")
}
func (UnimplementedAdminServiceServer) SendGlobalAlert(context.Context, *SendGlobalAlertRequest) (*SendGlobalAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendGlobalAlert not implemented")
}
func (UnimplementedAdminServiceServer) VerifyMasterKey(context.Context, *VerifyMasterKeyRequest) (*VerifyMasterKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyMasterKey not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetNetworkStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetNetworkStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetNetworkStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetNetworkStats(ctx, req.(*GetNetworkStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateUserRole(ctx, req.(*UpdateUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_BanNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).BanNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_BanNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).BanNode(ctx, req.(*BanNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UnbanNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbanNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UnbanNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UnbanNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UnbanNode(ctx, req.(*UnbanNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SendGlobalAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGlobalAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SendGlobalAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SendGlobalAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SendGlobalAlert(ctx, req.(*SendGlobalAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_VerifyMasterKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyMasterKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).VerifyMasterKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_VerifyMasterKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).VerifyMasterKey(ctx, req.(*VerifyMasterKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNetworkStats",
			Handler:    _AdminService_GetNetworkStats_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _AdminService_ListNodes_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _AdminService_ListUsers_Handler,
		},
		{
			MethodName: "UpdateUserRole",
			Handler:    _AdminService_UpdateUserRole_Handler,
		},
		{
			MethodName: "BanNode",
			Handler:    _AdminService_BanNode_Handler,
		},
		{
			MethodName: "UnbanNode",
			Handler:    _AdminService_UnbanNode_Handler,
		},
		{
			MethodName: "SendGlobalAlert",
			Handler:    _AdminService_SendGlobalAlert_Handler,
		},
		{
			MethodName: "VerifyMasterKey",
			Handler:    _AdminService_VerifyMasterKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
