// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: network.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tipo do nó na rede
type NodeType int32

const (
	NodeType_NODE_TYPE_UNSPECIFIED NodeType = 0
	NodeType_NODE_TYPE_DESKTOP     NodeType = 1 // Cliente desktop P2P (participa do grid computing)
	NodeType_NODE_TYPE_RELAY       NodeType = 2 // Servidor relay da comunidade (NAT Traversal + cache)
	NodeType_NODE_TYPE_MOBILE      NodeType = 3 // Cliente mobile (consumo apenas)
	NodeType_NODE_TYPE_WEB         NodeType = 4 // Cliente web (consumo apenas)
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNSPECIFIED",
		1: "NODE_TYPE_DESKTOP",
		2: "NODE_TYPE_RELAY",
		3: "NODE_TYPE_MOBILE",
		4: "NODE_TYPE_WEB",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNSPECIFIED": 0,
		"NODE_TYPE_DESKTOP":     1,
		"NODE_TYPE_RELAY":       2,
		"NODE_TYPE_MOBILE":      3,
		"NODE_TYPE_WEB":         4,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

// Status do nó
type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	NodeStatus_NODE_STATUS_ONLINE      NodeStatus = 1
	NodeStatus_NODE_STATUS_AWAY        NodeStatus = 2
	NodeStatus_NODE_STATUS_BUSY        NodeStatus = 3
	NodeStatus_NODE_STATUS_OFFLINE     NodeStatus = 4
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_ONLINE",
		2: "NODE_STATUS_AWAY",
		3: "NODE_STATUS_BUSY",
		4: "NODE_STATUS_OFFLINE",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_ONLINE":      1,
		"NODE_STATUS_AWAY":        2,
		"NODE_STATUS_BUSY":        3,
		"NODE_STATUS_OFFLINE":     4,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[1].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[1]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED    EventType = 0
	EventType_EVENT_TYPE_NODE_BANNED    EventType = 1 // Nó banido da rede
	EventType_EVENT_TYPE_CONTENT_BANNED EventType = 2 // Conteúdo específico banido
	EventType_EVENT_TYPE_GLOBAL_ALERT   EventType = 3 // Alerta global (manutenção, etc.)
	EventType_EVENT_TYPE_RELAY_OFFLINE  EventType = 4 // Relay ficou offline
	EventType_EVENT_TYPE_NETWORK_UPDATE EventType = 5 // Atualização de configuração da rede
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_NODE_BANNED",
		2: "EVENT_TYPE_CONTENT_BANNED",
		3: "EVENT_TYPE_GLOBAL_ALERT",
		4: "EVENT_TYPE_RELAY_OFFLINE",
		5: "EVENT_TYPE_NETWORK_UPDATE",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":    0,
		"EVENT_TYPE_NODE_BANNED":    1,
		"EVENT_TYPE_CONTENT_BANNED": 2,
		"EVENT_TYPE_GLOBAL_ALERT":   3,
		"EVENT_TYPE_RELAY_OFFLINE":  4,
		"EVENT_TYPE_NETWORK_UPDATE": 5,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{2}
}

// Identidade do nó baseada em chave pública Ed25519
type NodeIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID único derivado da chave pública (hex-encoded SHA256 dos primeiros 16 bytes)
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Chave pública Ed25519 (32 bytes, base64-encoded)
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Assinatura do node_id pela chave privada (prova de posse)
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIdentity) Reset() {
	*x = NodeIdentity{}
	mi := &file_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentity) ProtoMessage() {}

func (x *NodeIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentity.ProtoReflect.Descriptor instead.
func (*NodeIdentity) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

func (x *NodeIdentity) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeIdentity) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *NodeIdentity) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Informações completas do nó
type NodeInfo struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Identity *NodeIdentity          `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Type     NodeType               `protobuf:"varint,2,opt,name=type,proto3,enum=network.v1.NodeType" json:"type,omitempty"`
	Status   NodeStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=network.v1.NodeStatus" json:"status,omitempty"`
	// Endpoints para conexão direta (pode ter múltiplos para IPv4/IPv6)
	Endpoints []string `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// Versão do cliente
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// Capacidades especiais (e.g., "relay", "storage", "compute")
	Capabilities []string `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Região geográfica (para otimização de latência)
	Region string `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	// Timestamp de registro
	RegisteredAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	// Último heartbeat recebido
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetIdentity() *NodeIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *NodeInfo) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *NodeInfo) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *NodeInfo) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NodeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *NodeInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *NodeInfo) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *NodeInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *NodeIdentity          `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Type          NodeType               `protobuf:"varint,2,opt,name=type,proto3,enum=network.v1.NodeType" json:"type,omitempty"`
	Endpoints     []string               `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNodeRequest) GetIdentity() *NodeIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *RegisterNodeRequest) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *RegisterNodeRequest) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *RegisterNodeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterNodeRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterNodeRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type RegisterNodeResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// TTL em segundos para o próximo heartbeat
	HeartbeatIntervalSeconds int32 `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	// Lista inicial de relays sugeridos para o nó
	SuggestedRelays []*NodeInfo `protobuf:"bytes,4,rep,name=suggested_relays,json=suggestedRelays,proto3" json:"suggested_relays,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterNodeResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *RegisterNodeResponse) GetSuggestedRelays() []*NodeInfo {
	if x != nil {
		return x.SuggestedRelays
	}
	return nil
}

type HeartbeatRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Assinatura do timestamp atual pela chave privada do nó
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Status atual do nó
	Status NodeStatus `protobuf:"varint,3,opt,name=status,proto3,enum=network.v1.NodeStatus" json:"status,omitempty"`
	// Métricas opcionais de saúde
	Metrics       *NodeMetrics `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *HeartbeatRequest) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *HeartbeatRequest) GetMetrics() *NodeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type NodeMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uso de CPU (0-100)
	CpuUsage float32 `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	// Uso de memória (0-100)
	MemoryUsage float32 `protobuf:"fixed32,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	// Número de conexões P2P ativas
	ActiveConnections int32 `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	// Bandwidth disponível em Mbps
	AvailableBandwidthMbps float32 `protobuf:"fixed32,4,opt,name=available_bandwidth_mbps,json=availableBandwidthMbps,proto3" json:"available_bandwidth_mbps,omitempty"`
	// Latência média para o Core Server em ms
	LatencyMs     int32 `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{5}
}

func (x *NodeMetrics) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *NodeMetrics) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *NodeMetrics) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *NodeMetrics) GetAvailableBandwidthMbps() float32 {
	if x != nil {
		return x.AvailableBandwidthMbps
	}
	return 0
}

func (x *NodeMetrics) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type HeartbeatResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Próximo intervalo de heartbeat (pode ser ajustado dinamicamente)
	NextHeartbeatSeconds int32 `protobuf:"varint,2,opt,name=next_heartbeat_seconds,json=nextHeartbeatSeconds,proto3" json:"next_heartbeat_seconds,omitempty"`
	// Comandos pendentes para o nó (e.g., reconectar a outro relay)
	PendingCommands []*NodeCommand `protobuf:"bytes,3,rep,name=pending_commands,json=pendingCommands,proto3" json:"pending_commands,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetNextHeartbeatSeconds() int32 {
	if x != nil {
		return x.NextHeartbeatSeconds
	}
	return 0
}

func (x *HeartbeatResponse) GetPendingCommands() []*NodeCommand {
	if x != nil {
		return x.PendingCommands
	}
	return nil
}

type NodeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandType   string                 `protobuf:"bytes,2,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"` // "reconnect", "update", "migrate"
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                            // JSON serializado com parâmetros do comando
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCommand) Reset() {
	*x = NodeCommand{}
	mi := &file_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCommand) ProtoMessage() {}

func (x *NodeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCommand.ProtoReflect.Descriptor instead.
func (*NodeCommand) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{7}
}

func (x *NodeCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *NodeCommand) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *NodeCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GetActiveRelaysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Região preferida (opcional, para otimização de latência)
	PreferredRegion string `protobuf:"bytes,1,opt,name=preferred_region,json=preferredRegion,proto3" json:"preferred_region,omitempty"`
	// Número máximo de relays a retornar
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// IDs de relays a excluir (e.g., relays que já falharam)
	ExcludeNodeIds []string `protobuf:"bytes,3,rep,name=exclude_node_ids,json=excludeNodeIds,proto3" json:"exclude_node_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetActiveRelaysRequest) Reset() {
	*x = GetActiveRelaysRequest{}
	mi := &file_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveRelaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveRelaysRequest) ProtoMessage() {}

func (x *GetActiveRelaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveRelaysRequest.ProtoReflect.Descriptor instead.
func (*GetActiveRelaysRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{8}
}

func (x *GetActiveRelaysRequest) GetPreferredRegion() string {
	if x != nil {
		return x.PreferredRegion
	}
	return ""
}

func (x *GetActiveRelaysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetActiveRelaysRequest) GetExcludeNodeIds() []string {
	if x != nil {
		return x.ExcludeNodeIds
	}
	return nil
}

type GetActiveRelaysResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Relays []*NodeInfo            `protobuf:"bytes,1,rep,name=relays,proto3" json:"relays,omitempty"`
	// Timestamp da última atualização da lista
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveRelaysResponse) Reset() {
	*x = GetActiveRelaysResponse{}
	mi := &file_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveRelaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveRelaysResponse) ProtoMessage() {}

func (x *GetActiveRelaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveRelaysResponse.ProtoReflect.Descriptor instead.
func (*GetActiveRelaysResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{9}
}

func (x *GetActiveRelaysResponse) GetRelays() []*NodeInfo {
	if x != nil {
		return x.Relays
	}
	return nil
}

func (x *GetActiveRelaysResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SubscribeRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Tipos de eventos para filtrar (vazio = todos)
	EventTypes    []EventType `protobuf:"varint,2,rep,packed,name=event_types,json=eventTypes,proto3,enum=network.v1.EventType" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SubscribeRequest) GetEventTypes() []EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type GlobalEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Type      EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=network.v1.EventType" json:"type,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Payload específico do evento
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*GlobalEvent_NodeBanned
	//	*GlobalEvent_ContentBanned
	//	*GlobalEvent_GlobalAlert
	//	*GlobalEvent_RelayOffline
	//	*GlobalEvent_NetworkUpdate
	Payload isGlobalEvent_Payload `protobuf_oneof:"payload"`
	// Assinatura do moderador global que originou o evento
	ModeratorSignature *ModeratorSignature `protobuf:"bytes,20,opt,name=moderator_signature,json=moderatorSignature,proto3" json:"moderator_signature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GlobalEvent) Reset() {
	*x = GlobalEvent{}
	mi := &file_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalEvent) ProtoMessage() {}

func (x *GlobalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalEvent.ProtoReflect.Descriptor instead.
func (*GlobalEvent) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{11}
}

func (x *GlobalEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GlobalEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *GlobalEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GlobalEvent) GetPayload() isGlobalEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GlobalEvent) GetNodeBanned() *NodeBannedEvent {
	if x != nil {
		if x, ok := x.Payload.(*GlobalEvent_NodeBanned); ok {
			return x.NodeBanned
		}
	}
	return nil
}

func (x *GlobalEvent) GetContentBanned() *ContentBannedEvent {
	if x != nil {
		if x, ok := x.Payload.(*GlobalEvent_ContentBanned); ok {
			return x.ContentBanned
		}
	}
	return nil
}

func (x *GlobalEvent) GetGlobalAlert() *GlobalAlertEvent {
	if x != nil {
		if x, ok := x.Payload.(*GlobalEvent_GlobalAlert); ok {
			return x.GlobalAlert
		}
	}
	return nil
}

func (x *GlobalEvent) GetRelayOffline() *RelayOfflineEvent {
	if x != nil {
		if x, ok := x.Payload.(*GlobalEvent_RelayOffline); ok {
			return x.RelayOffline
		}
	}
	return nil
}

func (x *GlobalEvent) GetNetworkUpdate() *NetworkUpdateEvent {
	if x != nil {
		if x, ok := x.Payload.(*GlobalEvent_NetworkUpdate); ok {
			return x.NetworkUpdate
		}
	}
	return nil
}

func (x *GlobalEvent) GetModeratorSignature() *ModeratorSignature {
	if x != nil {
		return x.ModeratorSignature
	}
	return nil
}

type isGlobalEvent_Payload interface {
	isGlobalEvent_Payload()
}

type GlobalEvent_NodeBanned struct {
	NodeBanned *NodeBannedEvent `protobuf:"bytes,10,opt,name=node_banned,json=nodeBanned,proto3,oneof"`
}

type GlobalEvent_ContentBanned struct {
	ContentBanned *ContentBannedEvent `protobuf:"bytes,11,opt,name=content_banned,json=contentBanned,proto3,oneof"`
}

type GlobalEvent_GlobalAlert struct {
	GlobalAlert *GlobalAlertEvent `protobuf:"bytes,12,opt,name=global_alert,json=globalAlert,proto3,oneof"`
}

type GlobalEvent_RelayOffline struct {
	RelayOffline *RelayOfflineEvent `protobuf:"bytes,13,opt,name=relay_offline,json=relayOffline,proto3,oneof"`
}

type GlobalEvent_NetworkUpdate struct {
	NetworkUpdate *NetworkUpdateEvent `protobuf:"bytes,14,opt,name=network_update,json=networkUpdate,proto3,oneof"`
}

func (*GlobalEvent_NodeBanned) isGlobalEvent_Payload() {}

func (*GlobalEvent_ContentBanned) isGlobalEvent_Payload() {}

func (*GlobalEvent_GlobalAlert) isGlobalEvent_Payload() {}

func (*GlobalEvent_RelayOffline) isGlobalEvent_Payload() {}

func (*GlobalEvent_NetworkUpdate) isGlobalEvent_Payload() {}

type NodeBannedEvent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	BannedNodeId string                 `protobuf:"bytes,1,opt,name=banned_node_id,json=bannedNodeId,proto3" json:"banned_node_id,omitempty"`
	Reason       string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Duração do ban em segundos (0 = permanente)
	DurationSeconds int64 `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	// Hash do conteúdo que motivou o ban (para referência)
	EvidenceHash  string `protobuf:"bytes,4,opt,name=evidence_hash,json=evidenceHash,proto3" json:"evidence_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeBannedEvent) Reset() {
	*x = NodeBannedEvent{}
	mi := &file_network_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeBannedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeBannedEvent) ProtoMessage() {}

func (x *NodeBannedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeBannedEvent.ProtoReflect.Descriptor instead.
func (*NodeBannedEvent) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{12}
}

func (x *NodeBannedEvent) GetBannedNodeId() string {
	if x != nil {
		return x.BannedNodeId
	}
	return ""
}

func (x *NodeBannedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *NodeBannedEvent) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *NodeBannedEvent) GetEvidenceHash() string {
	if x != nil {
		return x.EvidenceHash
	}
	return ""
}

type ContentBannedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hash do conteúdo banido (SHA256)
	ContentHash string `protobuf:"bytes,1,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Reason      string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Categoria do conteúdo (para filtragem)
	Category      string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBannedEvent) Reset() {
	*x = ContentBannedEvent{}
	mi := &file_network_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBannedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBannedEvent) ProtoMessage() {}

func (x *ContentBannedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBannedEvent.ProtoReflect.Descriptor instead.
func (*ContentBannedEvent) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{13}
}

func (x *ContentBannedEvent) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *ContentBannedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ContentBannedEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GlobalAlertEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Title   string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Nível de severidade (info, warning, critical)
	Severity string `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	// URL opcional com mais informações
	InfoUrl       string `protobuf:"bytes,4,opt,name=info_url,json=infoUrl,proto3" json:"info_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalAlertEvent) Reset() {
	*x = GlobalAlertEvent{}
	mi := &file_network_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalAlertEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalAlertEvent) ProtoMessage() {}

func (x *GlobalAlertEvent) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalAlertEvent.ProtoReflect.Descriptor instead.
func (*GlobalAlertEvent) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{14}
}

func (x *GlobalAlertEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GlobalAlertEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GlobalAlertEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *GlobalAlertEvent) GetInfoUrl() string {
	if x != nil {
		return x.InfoUrl
	}
	return ""
}

type RelayOfflineEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RelayNodeId string                 `protobuf:"bytes,1,opt,name=relay_node_id,json=relayNodeId,proto3" json:"relay_node_id,omitempty"`
	Reason      string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Relays alternativos sugeridos
	AlternativeRelayIds []string `protobuf:"bytes,3,rep,name=alternative_relay_ids,json=alternativeRelayIds,proto3" json:"alternative_relay_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RelayOfflineEvent) Reset() {
	*x = RelayOfflineEvent{}
	mi := &file_network_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayOfflineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayOfflineEvent) ProtoMessage() {}

func (x *RelayOfflineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayOfflineEvent.ProtoReflect.Descriptor instead.
func (*RelayOfflineEvent) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{15}
}

func (x *RelayOfflineEvent) GetRelayNodeId() string {
	if x != nil {
		return x.RelayNodeId
	}
	return ""
}

func (x *RelayOfflineEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RelayOfflineEvent) GetAlternativeRelayIds() []string {
	if x != nil {
		return x.AlternativeRelayIds
	}
	return nil
}

type NetworkUpdateEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UpdateType string                 `protobuf:"bytes,1,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"` // "config", "protocol", "feature"
	Payload    []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                         // JSON serializado
	// Indica se requer reinício do cliente
	RequiresRestart bool `protobuf:"varint,3,opt,name=requires_restart,json=requiresRestart,proto3" json:"requires_restart,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkUpdateEvent) Reset() {
	*x = NetworkUpdateEvent{}
	mi := &file_network_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkUpdateEvent) ProtoMessage() {}

func (x *NetworkUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkUpdateEvent.ProtoReflect.Descriptor instead.
func (*NetworkUpdateEvent) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{16}
}

func (x *NetworkUpdateEvent) GetUpdateType() string {
	if x != nil {
		return x.UpdateType
	}
	return ""
}

func (x *NetworkUpdateEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NetworkUpdateEvent) GetRequiresRestart() bool {
	if x != nil {
		return x.RequiresRestart
	}
	return false
}

type ModeratorSignature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID do moderador (derivado da chave pública)
	ModeratorId string `protobuf:"bytes,1,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	// Chave pública do moderador (deve estar na lista de chaves mestres)
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Assinatura Ed25519 do evento serializado (sem este campo)
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// Timestamp da assinatura
	SignedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeratorSignature) Reset() {
	*x = ModeratorSignature{}
	mi := &file_network_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeratorSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeratorSignature) ProtoMessage() {}

func (x *ModeratorSignature) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeratorSignature.ProtoReflect.Descriptor instead.
func (*ModeratorSignature) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{17}
}

func (x *ModeratorSignature) GetModeratorId() string {
	if x != nil {
		return x.ModeratorId
	}
	return ""
}

func (x *ModeratorSignature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ModeratorSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ModeratorSignature) GetSignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SignedAt
	}
	return nil
}

type CheckForUpdateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentVersion string                 `protobuf:"bytes,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	Platform       string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"` // "windows", "linux", "darwin"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckForUpdateRequest) Reset() {
	*x = CheckForUpdateRequest{}
	mi := &file_network_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckForUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForUpdateRequest) ProtoMessage() {}

func (x *CheckForUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForUpdateRequest.ProtoReflect.Descriptor instead.
func (*CheckForUpdateRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{18}
}

func (x *CheckForUpdateRequest) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *CheckForUpdateRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type CheckForUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Critical      bool                   `protobuf:"varint,4,opt,name=critical,proto3" json:"critical,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckForUpdateResponse) Reset() {
	*x = CheckForUpdateResponse{}
	mi := &file_network_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckForUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForUpdateResponse) ProtoMessage() {}

func (x *CheckForUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForUpdateResponse.ProtoReflect.Descriptor instead.
func (*CheckForUpdateResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{19}
}

func (x *CheckForUpdateResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckForUpdateResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CheckForUpdateResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CheckForUpdateResponse) GetCritical() bool {
	if x != nil {
		return x.Critical
	}
	return false
}

var File_network_proto protoreflect.FileDescriptor

const file_network_proto_rawDesc = "" +
	"\n" +
	"\rnetwork.proto\x12\n" +
	"network.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n" +
	"\fNodeIdentity\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\x88\x03\n" +
	"\bNodeInfo\x124\n" +
	"\bidentity\x18\x01 \x01(\v2\x18.network.v1.NodeIdentityR\bidentity\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.network.v1.NodeTypeR\x04type\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.network.v1.NodeStatusR\x06status\x12\x1c\n" +
	"\tendpoints\x18\x04 \x03(\tR\tendpoints\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12?\n" +
	"\rregistered_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x127\n" +
	"\tlast_seen\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"\xe9\x01\n" +
	"\x13RegisterNodeRequest\x124\n" +
	"\bidentity\x18\x01 \x01(\v2\x18.network.v1.NodeIdentityR\bidentity\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.network.v1.NodeTypeR\x04type\x12\x1c\n" +
	"\tendpoints\x18\x03 \x03(\tR\tendpoints\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\"\xc9\x01\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\x05R\x18heartbeatIntervalSeconds\x12?\n" +
	"\x10suggested_relays\x18\x04 \x03(\v2\x14.network.v1.NodeInfoR\x0fsuggestedRelays\"\xac\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.network.v1.NodeStatusR\x06status\x121\n" +
	"\ametrics\x18\x04 \x01(\v2\x17.network.v1.NodeMetricsR\ametrics\"\xd5\x01\n" +
	"\vNodeMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x02R\vmemoryUsage\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x05R\x11activeConnections\x128\n" +
	"\x18available_bandwidth_mbps\x18\x04 \x01(\x02R\x16availableBandwidthMbps\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x05R\tlatencyMs\"\xa7\x01\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\x16next_heartbeat_seconds\x18\x02 \x01(\x05R\x14nextHeartbeatSeconds\x12B\n" +
	"\x10pending_commands\x18\x03 \x03(\v2\x17.network.v1.NodeCommandR\x0fpendingCommands\"i\n" +
	"\vNodeCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\fcommand_type\x18\x02 \x01(\tR\vcommandType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x83\x01\n" +
	"\x16GetActiveRelaysRequest\x12)\n" +
	"\x10preferred_region\x18\x01 \x01(\tR\x0fpreferredRegion\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12(\n" +
	"\x10exclude_node_ids\x18\x03 \x03(\tR\x0eexcludeNodeIds\"\x82\x01\n" +
	"\x17GetActiveRelaysResponse\x12,\n" +
	"\x06relays\x18\x01 \x03(\v2\x14.network.v1.NodeInfoR\x06relays\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"c\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x126\n" +
	"\vevent_types\x18\x02 \x03(\x0e2\x15.network.v1.EventTypeR\n" +
	"eventTypes\"\xc4\x04\n" +
	"\vGlobalEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.network.v1.EventTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12>\n" +
	"\vnode_banned\x18\n" +
	" \x01(\v2\x1b.network.v1.NodeBannedEventH\x00R\n" +
	"nodeBanned\x12G\n" +
	"\x0econtent_banned\x18\v \x01(\v2\x1e.network.v1.ContentBannedEventH\x00R\rcontentBanned\x12A\n" +
	"\fglobal_alert\x18\f \x01(\v2\x1c.network.v1.GlobalAlertEventH\x00R\vglobalAlert\x12D\n" +
	"\rrelay_offline\x18\r \x01(\v2\x1d.network.v1.RelayOfflineEventH\x00R\frelayOffline\x12G\n" +
	"\x0enetwork_update\x18\x0e \x01(\v2\x1e.network.v1.NetworkUpdateEventH\x00R\rnetworkUpdate\x12O\n" +
	"\x13moderator_signature\x18\x14 \x01(\v2\x1e.network.v1.ModeratorSignatureR\x12moderatorSignatureB\t\n" +
	"\apayload\"\x9f\x01\n" +
	"\x0fNodeBannedEvent\x12$\n" +
	"\x0ebanned_node_id\x18\x01 \x01(\tR\fbannedNodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x03R\x0fdurationSeconds\x12#\n" +
	"\revidence_hash\x18\x04 \x01(\tR\fevidenceHash\"k\n" +
	"\x12ContentBannedEvent\x12!\n" +
	"\fcontent_hash\x18\x01 \x01(\tR\vcontentHash\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"y\n" +
	"\x10GlobalAlertEvent\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x19\n" +
	"\binfo_url\x18\x04 \x01(\tR\ainfoUrl\"\x83\x01\n" +
	"\x11RelayOfflineEvent\x12\"\n" +
	"\rrelay_node_id\x18\x01 \x01(\tR\vrelayNodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x122\n" +
	"\x15alternative_relay_ids\x18\x03 \x03(\tR\x13alternativeRelayIds\"z\n" +
	"\x12NetworkUpdateEvent\x12\x1f\n" +
	"\vupdate_type\x18\x01 \x01(\tR\n" +
	"updateType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12)\n" +
	"\x10requires_restart\x18\x03 \x01(\bR\x0frequiresRestart\"\xad\x01\n" +
	"\x12ModeratorSignature\x12!\n" +
	"\fmoderator_id\x18\x01 \x01(\tR\vmoderatorId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x127\n" +
	"\tsigned_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bsignedAt\"\\\n" +
	"\x15CheckForUpdateRequest\x12'\n" +
	"\x0fcurrent_version\x18\x01 \x01(\tR\x0ecurrentVersion\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"~\n" +
	"\x16CheckForUpdateResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\bcritical\x18\x04 \x01(\bR\bcritical*z\n" +
	"\bNodeType\x12\x19\n" +
	"\x15NODE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11NODE_TYPE_DESKTOP\x10\x01\x12\x13\n" +
	"\x0fNODE_TYPE_RELAY\x10\x02\x12\x14\n" +
	"\x10NODE_TYPE_MOBILE\x10\x03\x12\x11\n" +
	"\rNODE_TYPE_WEB\x10\x04*\x86\x01\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ONLINE\x10\x01\x12\x14\n" +
	"\x10NODE_STATUS_AWAY\x10\x02\x12\x14\n" +
	"\x10NODE_STATUS_BUSY\x10\x03\x12\x17\n" +
	"\x13NODE_STATUS_OFFLINE\x10\x04*\xbc\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16EVENT_TYPE_NODE_BANNED\x10\x01\x12\x1d\n" +
	"\x19EVENT_TYPE_CONTENT_BANNED\x10\x02\x12\x1b\n" +
	"\x17EVENT_TYPE_GLOBAL_ALERT\x10\x03\x12\x1c\n" +
	"\x18EVENT_TYPE_RELAY_OFFLINE\x10\x04\x12\x1d\n" +
	"\x19EVENT_TYPE_NETWORK_UPDATE\x10\x052\xdd\x02\n" +
	"\x0eNetworkService\x12Q\n" +
	"\fRegisterNode\x12\x1f.network.v1.RegisterNodeRequest\x1a .network.v1.RegisterNodeResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.network.v1.HeartbeatRequest\x1a\x1d.network.v1.HeartbeatResponse\x12Z\n" +
	"\x0fGetActiveRelays\x12\".network.v1.GetActiveRelaysRequest\x1a#.network.v1.GetActiveRelaysResponse\x12R\n" +
	"\x17SubscribeToGlobalEvents\x12\x1c.network.v1.SubscribeRequest\x1a\x17.network.v1.GlobalEvent0\x012h\n" +
	"\rUpdateService\x12W\n" +
	"\x0eCheckForUpdate\x12!.network.v1.CheckForUpdateRequest\x1a\".network.v1.CheckForUpdateResponseB3Z1github.com/goautomatik/core-server/pkg/pb/v1;pbv1b\x06proto3"

var (
	file_network_proto_rawDescOnce sync.Once
	file_network_proto_rawDescData []byte
)

func file_network_proto_rawDescGZIP() []byte {
	file_network_proto_rawDescOnce.Do(func() {
		file_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)))
	})
	return file_network_proto_rawDescData
}

var file_network_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_network_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_network_proto_goTypes = []any{
	(NodeType)(0),                   // 0: network.v1.NodeType
	(NodeStatus)(0),                 // 1: network.v1.NodeStatus
	(EventType)(0),                  // 2: network.v1.EventType
	(*NodeIdentity)(nil),            // 3: network.v1.NodeIdentity
	(*NodeInfo)(nil),                // 4: network.v1.NodeInfo
	(*RegisterNodeRequest)(nil),     // 5: network.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),    // 6: network.v1.RegisterNodeResponse
	(*HeartbeatRequest)(nil),        // 7: network.v1.HeartbeatRequest
	(*NodeMetrics)(nil),             // 8: network.v1.NodeMetrics
	(*HeartbeatResponse)(nil),       // 9: network.v1.HeartbeatResponse
	(*NodeCommand)(nil),             // 10: network.v1.NodeCommand
	(*GetActiveRelaysRequest)(nil),  // 11: network.v1.GetActiveRelaysRequest
	(*GetActiveRelaysResponse)(nil), // 12: network.v1.GetActiveRelaysResponse
	(*SubscribeRequest)(nil),        // 13: network.v1.SubscribeRequest
	(*GlobalEvent)(nil),             // 14: network.v1.GlobalEvent
	(*NodeBannedEvent)(nil),         // 15: network.v1.NodeBannedEvent
	(*ContentBannedEvent)(nil),      // 16: network.v1.ContentBannedEvent
	(*GlobalAlertEvent)(nil),        // 17: network.v1.GlobalAlertEvent
	(*RelayOfflineEvent)(nil),       // 18: network.v1.RelayOfflineEvent
	(*NetworkUpdateEvent)(nil),      // 19: network.v1.NetworkUpdateEvent
	(*ModeratorSignature)(nil),      // 20: network.v1.ModeratorSignature
	(*CheckForUpdateRequest)(nil),   // 21: network.v1.CheckForUpdateRequest
	(*CheckForUpdateResponse)(nil),  // 22: network.v1.CheckForUpdateResponse
	(*timestamppb.Timestamp)(nil),   // 23: google.protobuf.Timestamp
}
var file_network_proto_depIdxs = []int32{
	3,  // 0: network.v1.NodeInfo.identity:type_name -> network.v1.NodeIdentity
	0,  // 1: network.v1.NodeInfo.type:type_name -> network.v1.NodeType
	1,  // 2: network.v1.NodeInfo.status:type_name -> network.v1.NodeStatus
	23, // 3: network.v1.NodeInfo.registered_at:type_name -> google.protobuf.Timestamp
	23, // 4: network.v1.NodeInfo.last_seen:type_name -> google.protobuf.Timestamp
	3,  // 5: network.v1.RegisterNodeRequest.identity:type_name -> network.v1.NodeIdentity
	0,  // 6: network.v1.RegisterNodeRequest.type:type_name -> network.v1.NodeType
	4,  // 7: network.v1.RegisterNodeResponse.suggested_relays:type_name -> network.v1.NodeInfo
	1,  // 8: network.v1.HeartbeatRequest.status:type_name -> network.v1.NodeStatus
	8,  // 9: network.v1.HeartbeatRequest.metrics:type_name -> network.v1.NodeMetrics
	10, // 10: network.v1.HeartbeatResponse.pending_commands:type_name -> network.v1.NodeCommand
	4,  // 11: network.v1.GetActiveRelaysResponse.relays:type_name -> network.v1.NodeInfo
	23, // 12: network.v1.GetActiveRelaysResponse.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 13: network.v1.SubscribeRequest.event_types:type_name -> network.v1.EventType
	2,  // 14: network.v1.GlobalEvent.type:type_name -> network.v1.EventType
	23, // 15: network.v1.GlobalEvent.timestamp:type_name -> google.protobuf.Timestamp
	15, // 16: network.v1.GlobalEvent.node_banned:type_name -> network.v1.NodeBannedEvent
	16, // 17: network.v1.GlobalEvent.content_banned:type_name -> network.v1.ContentBannedEvent
	17, // 18: network.v1.GlobalEvent.global_alert:type_name -> network.v1.GlobalAlertEvent
	18, // 19: network.v1.GlobalEvent.relay_offline:type_name -> network.v1.RelayOfflineEvent
	19, // 20: network.v1.GlobalEvent.network_update:type_name -> network.v1.NetworkUpdateEvent
	20, // 21: network.v1.GlobalEvent.moderator_signature:type_name -> network.v1.ModeratorSignature
	23, // 22: network.v1.ModeratorSignature.signed_at:type_name -> google.protobuf.Timestamp
	5,  // 23: network.v1.NetworkService.RegisterNode:input_type -> network.v1.RegisterNodeRequest
	7,  // 24: network.v1.NetworkService.Heartbeat:input_type -> network.v1.HeartbeatRequest
	11, // 25: network.v1.NetworkService.GetActiveRelays:input_type -> network.v1.GetActiveRelaysRequest
	13, // 26: network.v1.NetworkService.SubscribeToGlobalEvents:input_type -> network.v1.SubscribeRequest
	21, // 27: network.v1.UpdateService.CheckForUpdate:input_type -> network.v1.CheckForUpdateRequest
	6,  // 28: network.v1.NetworkService.RegisterNode:output_type -> network.v1.RegisterNodeResponse
	9,  // 29: network.v1.NetworkService.Heartbeat:output_type -> network.v1.HeartbeatResponse
	12, // 30: network.v1.NetworkService.GetActiveRelays:output_type -> network.v1.GetActiveRelaysResponse
	14, // 31: network.v1.NetworkService.SubscribeToGlobalEvents:output_type -> network.v1.GlobalEvent
	22, // 32: network.v1.UpdateService.CheckForUpdate:output_type -> network.v1.CheckForUpdateResponse
	28, // [28:33] is the sub-list for method output_type
	23, // [23:28] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	file_network_proto_msgTypes[11].OneofWrappers = []any{
		(*GlobalEvent_NodeBanned)(nil),
		(*GlobalEvent_ContentBanned)(nil),
		(*GlobalEvent_GlobalAlert)(nil),
		(*GlobalEvent_RelayOffline)(nil),
		(*GlobalEvent_NetworkUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
		EnumInfos:         file_network_proto_enumTypes,
		MessageInfos:      file_network_proto_msgTypes,
	}.Build()
	File_network_proto = out.File
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
