// Code generated by simplified proto generator. DO NOT EDIT.
// source: relay.proto

package pbv1

import (
	"google.golang.org/protobuf/types/known/timestamppb"
)

// MessageType para roteamento
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_CHAT        MessageType = 1
	MessageType_MESSAGE_TYPE_FILE_CHUNK  MessageType = 2
	MessageType_MESSAGE_TYPE_SIGNALING   MessageType = 3
	MessageType_MESSAGE_TYPE_PRESENCE    MessageType = 4
	MessageType_MESSAGE_TYPE_ACK         MessageType = 5
	MessageType_MESSAGE_TYPE_CONTROL     MessageType = 6
)

// Priority para QoS
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_NORMAL      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
	Priority_PRIORITY_URGENT      Priority = 4
)

// DeliveryStatus para recibos
type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_DELIVERED   DeliveryStatus = 1
	DeliveryStatus_DELIVERY_STATUS_QUEUED      DeliveryStatus = 2
	DeliveryStatus_DELIVERY_STATUS_FAILED      DeliveryStatus = 3
	DeliveryStatus_DELIVERY_STATUS_REJECTED    DeliveryStatus = 4
	DeliveryStatus_DELIVERY_STATUS_EXPIRED     DeliveryStatus = 5
)

// Envelope representa uma mensagem cifrada encapsulada
type Envelope struct {
	MessageId        string                 `json:"message_id,omitempty"`
	SenderNodeId     string                 `json:"sender_node_id,omitempty"`
	TargetNodeId     string                 `json:"target_node_id,omitempty"`
	EncryptedPayload []byte                 `json:"encrypted_payload,omitempty"`
	Nonce            []byte                 `json:"nonce,omitempty"`
	SenderSignature  []byte                 `json:"sender_signature,omitempty"`
	Timestamp        *timestamppb.Timestamp `json:"timestamp,omitempty"`
	MessageType      MessageType            `json:"message_type,omitempty"`
	TtlSeconds       int32                  `json:"ttl_seconds,omitempty"`
	Priority         Priority               `json:"priority,omitempty"`
}

// ConnectRequest para registro no Relay
type ConnectRequest struct {
	NodeId       string   `json:"node_id,omitempty"`
	PublicKey    []byte   `json:"public_key,omitempty"`
	Signature    []byte   `json:"signature,omitempty"`
	Capabilities []string `json:"capabilities,omitempty"`
}

// ConnectResponse resposta de registro
type ConnectResponse struct {
	Success          bool     `json:"success,omitempty"`
	Message          string   `json:"message,omitempty"`
	SessionId        string   `json:"session_id,omitempty"`
	ConnectedNodeIds []string `json:"connected_node_ids,omitempty"`
}

// NodeQueryRequest consulta de nó
type NodeQueryRequest struct {
	NodeId string `json:"node_id,omitempty"`
}

// NodeQueryResponse resposta de consulta
type NodeQueryResponse struct {
	Connected    bool                   `json:"connected,omitempty"`
	LastActivity *timestamppb.Timestamp `json:"last_activity,omitempty"`
}

// DeliveryReceipt recibo de entrega
type DeliveryReceipt struct {
	MessageId    string                 `json:"message_id,omitempty"`
	Status       DeliveryStatus         `json:"status,omitempty"`
	ErrorMessage string                 `json:"error_message,omitempty"`
	Timestamp    *timestamppb.Timestamp `json:"timestamp,omitempty"`
}
