// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: relay.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tipos de mensagem (para roteamento eficiente)
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_CHAT        MessageType = 1 // Mensagem de chat
	MessageType_MESSAGE_TYPE_FILE_CHUNK  MessageType = 2 // Chunk de arquivo
	MessageType_MESSAGE_TYPE_SIGNALING   MessageType = 3 // ICE/SDP para WebRTC
	MessageType_MESSAGE_TYPE_PRESENCE    MessageType = 4 // Atualização de presença
	MessageType_MESSAGE_TYPE_ACK         MessageType = 5 // Confirmação de recebimento
	MessageType_MESSAGE_TYPE_CONTROL     MessageType = 6 // Mensagem de controle
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_CHAT",
		2: "MESSAGE_TYPE_FILE_CHUNK",
		3: "MESSAGE_TYPE_SIGNALING",
		4: "MESSAGE_TYPE_PRESENCE",
		5: "MESSAGE_TYPE_ACK",
		6: "MESSAGE_TYPE_CONTROL",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_CHAT":        1,
		"MESSAGE_TYPE_FILE_CHUNK":  2,
		"MESSAGE_TYPE_SIGNALING":   3,
		"MESSAGE_TYPE_PRESENCE":    4,
		"MESSAGE_TYPE_ACK":         5,
		"MESSAGE_TYPE_CONTROL":     6,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_relay_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

// Prioridades de mensagem
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_NORMAL      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
	Priority_PRIORITY_URGENT      Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_URGENT",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_URGENT":      4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_relay_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_DELIVERED   DeliveryStatus = 1 // Entregue ao destinatário
	DeliveryStatus_DELIVERY_STATUS_QUEUED      DeliveryStatus = 2 // Na fila (destinatário offline)
	DeliveryStatus_DELIVERY_STATUS_FAILED      DeliveryStatus = 3 // Falha na entrega
	DeliveryStatus_DELIVERY_STATUS_REJECTED    DeliveryStatus = 4 // Rejeitado (remetente banido)
	DeliveryStatus_DELIVERY_STATUS_EXPIRED     DeliveryStatus = 5 // TTL expirou
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_DELIVERED",
		2: "DELIVERY_STATUS_QUEUED",
		3: "DELIVERY_STATUS_FAILED",
		4: "DELIVERY_STATUS_REJECTED",
		5: "DELIVERY_STATUS_EXPIRED",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED": 0,
		"DELIVERY_STATUS_DELIVERED":   1,
		"DELIVERY_STATUS_QUEUED":      2,
		"DELIVERY_STATUS_FAILED":      3,
		"DELIVERY_STATUS_REJECTED":    4,
		"DELIVERY_STATUS_EXPIRED":     5,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_proto_enumTypes[2].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_relay_proto_enumTypes[2]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{2}
}

// Envelope representa uma mensagem cifrada que o Relay encaminha sem ler
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID único da mensagem
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// NodeID do remetente
	SenderNodeId string `protobuf:"bytes,2,opt,name=sender_node_id,json=senderNodeId,proto3" json:"sender_node_id,omitempty"`
	// NodeID do destinatário
	TargetNodeId string `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	// Payload cifrado (E2E encrypted - o Relay não pode ler)
	// Contém a mensagem real serializada
	EncryptedPayload []byte `protobuf:"bytes,4,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	// Nonce/IV usado na criptografia (para replay protection)
	Nonce []byte `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Assinatura do remetente sobre (message_id + target_node_id + hash(payload))
	SenderSignature []byte `protobuf:"bytes,6,opt,name=sender_signature,json=senderSignature,proto3" json:"sender_signature,omitempty"`
	// Timestamp da mensagem
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Tipo de mensagem (para roteamento sem ler conteúdo)
	MessageType MessageType `protobuf:"varint,8,opt,name=message_type,json=messageType,proto3,enum=relay.v1.MessageType" json:"message_type,omitempty"`
	// TTL em segundos (mensagem expira após esse tempo)
	TtlSeconds int32 `protobuf:"varint,9,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Prioridade (para QoS)
	Priority      Priority `protobuf:"varint,10,opt,name=priority,proto3,enum=relay.v1.Priority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetSenderNodeId() string {
	if x != nil {
		return x.SenderNodeId
	}
	return ""
}

func (x *Envelope) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *Envelope) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *Envelope) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Envelope) GetSenderSignature() []byte {
	if x != nil {
		return x.SenderSignature
	}
	return nil
}

func (x *Envelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Envelope) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Envelope) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *Envelope) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

type ConnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identidade completa do nó
	NodeId    string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Assinatura do node_id
	// Capacidades do nó
	Capabilities  []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ConnectRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ConnectRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ConnectRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ConnectResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// ID da sessão neste Relay
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Lista de nós atualmente conectados (opcional, para discovery local)
	ConnectedNodeIds []string `protobuf:"bytes,4,rep,name=connected_node_ids,json=connectedNodeIds,proto3" json:"connected_node_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectResponse) GetConnectedNodeIds() []string {
	if x != nil {
		return x.ConnectedNodeIds
	}
	return nil
}

type NodeQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeQueryRequest) Reset() {
	*x = NodeQueryRequest{}
	mi := &file_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeQueryRequest) ProtoMessage() {}

func (x *NodeQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeQueryRequest.ProtoReflect.Descriptor instead.
func (*NodeQueryRequest) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{3}
}

func (x *NodeQueryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type NodeQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	LastActivity  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeQueryResponse) Reset() {
	*x = NodeQueryResponse{}
	mi := &file_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeQueryResponse) ProtoMessage() {}

func (x *NodeQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeQueryResponse.ProtoReflect.Descriptor instead.
func (*NodeQueryResponse) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{4}
}

func (x *NodeQueryResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *NodeQueryResponse) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

// Resposta de entrega (enviada de volta ao remetente)
type DeliveryReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        DeliveryStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=relay.v1.DeliveryStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryReceipt) Reset() {
	*x = DeliveryReceipt{}
	mi := &file_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryReceipt) ProtoMessage() {}

func (x *DeliveryReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryReceipt.ProtoReflect.Descriptor instead.
func (*DeliveryReceipt) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryReceipt) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeliveryReceipt) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *DeliveryReceipt) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeliveryReceipt) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_relay_proto protoreflect.FileDescriptor

const file_relay_proto_rawDesc = "" +
	"\n" +
	"\vrelay.proto\x12\brelay.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x03\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12$\n" +
	"\x0esender_node_id\x18\x02 \x01(\tR\fsenderNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeId\x12+\n" +
	"\x11encrypted_payload\x18\x04 \x01(\fR\x10encryptedPayload\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\fR\x05nonce\x12)\n" +
	"\x10sender_signature\x18\x06 \x01(\fR\x0fsenderSignature\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x128\n" +
	"\fmessage_type\x18\b \x01(\x0e2\x15.relay.v1.MessageTypeR\vmessageType\x12\x1f\n" +
	"\vttl_seconds\x18\t \x01(\x05R\n" +
	"ttlSeconds\x12.\n" +
	"\bpriority\x18\n" +
	" \x01(\x0e2\x12.relay.v1.PriorityR\bpriority\"\x8a\x01\n" +
	"\x0eConnectRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"\x92\x01\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12,\n" +
	"\x12connected_node_ids\x18\x04 \x03(\tR\x10connectedNodeIds\"+\n" +
	"\x10NodeQueryRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"r\n" +
	"\x11NodeQueryResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12?\n" +
	"\rlast_activity\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\"\xc1\x01\n" +
	"\x0fDeliveryReceipt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.relay.v1.DeliveryStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*\xc6\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_CHAT\x10\x01\x12\x1b\n" +
	"\x17MESSAGE_TYPE_FILE_CHUNK\x10\x02\x12\x1a\n" +
	"\x16MESSAGE_TYPE_SIGNALING\x10\x03\x12\x19\n" +
	"\x15MESSAGE_TYPE_PRESENCE\x10\x04\x12\x14\n" +
	"\x10MESSAGE_TYPE_ACK\x10\x05\x12\x18\n" +
	"\x14MESSAGE_TYPE_CONTROL\x10\x06*s\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x13\n" +
	"\x0fPRIORITY_URGENT\x10\x04*\xc3\x01\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DELIVERY_STATUS_DELIVERED\x10\x01\x12\x1a\n" +
	"\x16DELIVERY_STATUS_QUEUED\x10\x02\x12\x1a\n" +
	"\x16DELIVERY_STATUS_FAILED\x10\x03\x12\x1c\n" +
	"\x18DELIVERY_STATUS_REJECTED\x10\x04\x12\x1b\n" +
	"\x17DELIVERY_STATUS_EXPIRED\x10\x052\xdf\x01\n" +
	"\fRelayService\x12<\n" +
	"\x0eStreamMessages\x12\x12.relay.v1.Envelope\x1a\x12.relay.v1.Envelope(\x010\x01\x12E\n" +
	"\x0eConnectToRelay\x12\x18.relay.v1.ConnectRequest\x1a\x19.relay.v1.ConnectResponse\x12J\n" +
	"\x0fIsNodeConnected\x12\x1a.relay.v1.NodeQueryRequest\x1a\x1b.relay.v1.NodeQueryResponseB3Z1github.com/goautomatik/core-server/pkg/pb/v1;pbv1b\x06proto3"

var (
	file_relay_proto_rawDescOnce sync.Once
	file_relay_proto_rawDescData []byte
)

func file_relay_proto_rawDescGZIP() []byte {
	file_relay_proto_rawDescOnce.Do(func() {
		file_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)))
	})
	return file_relay_proto_rawDescData
}

var file_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_relay_proto_goTypes = []any{
	(MessageType)(0),              // 0: relay.v1.MessageType
	(Priority)(0),                 // 1: relay.v1.Priority
	(DeliveryStatus)(0),           // 2: relay.v1.DeliveryStatus
	(*Envelope)(nil),              // 3: relay.v1.Envelope
	(*ConnectRequest)(nil),        // 4: relay.v1.ConnectRequest
	(*ConnectResponse)(nil),       // 5: relay.v1.ConnectResponse
	(*NodeQueryRequest)(nil),      // 6: relay.v1.NodeQueryRequest
	(*NodeQueryResponse)(nil),     // 7: relay.v1.NodeQueryResponse
	(*DeliveryReceipt)(nil),       // 8: relay.v1.DeliveryReceipt
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_relay_proto_depIdxs = []int32{
	9, // 0: relay.v1.Envelope.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: relay.v1.Envelope.message_type:type_name -> relay.v1.MessageType
	1, // 2: relay.v1.Envelope.priority:type_name -> relay.v1.Priority
	9, // 3: relay.v1.NodeQueryResponse.last_activity:type_name -> google.protobuf.Timestamp
	2, // 4: relay.v1.DeliveryReceipt.status:type_name -> relay.v1.DeliveryStatus
	9, // 5: relay.v1.DeliveryReceipt.timestamp:type_name -> google.protobuf.Timestamp
	3, // 6: relay.v1.RelayService.StreamMessages:input_type -> relay.v1.Envelope
	4, // 7: relay.v1.RelayService.ConnectToRelay:input_type -> relay.v1.ConnectRequest
	6, // 8: relay.v1.RelayService.IsNodeConnected:input_type -> relay.v1.NodeQueryRequest
	3, // 9: relay.v1.RelayService.StreamMessages:output_type -> relay.v1.Envelope
	5, // 10: relay.v1.RelayService.ConnectToRelay:output_type -> relay.v1.ConnectResponse
	7, // 11: relay.v1.RelayService.IsNodeConnected:output_type -> relay.v1.NodeQueryResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_relay_proto_init() }
func file_relay_proto_init() {
	if File_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relay_proto_goTypes,
		DependencyIndexes: file_relay_proto_depIdxs,
		EnumInfos:         file_relay_proto_enumTypes,
		MessageInfos:      file_relay_proto_msgTypes,
	}.Build()
	File_relay_proto = out.File
	file_relay_proto_goTypes = nil
	file_relay_proto_depIdxs = nil
}
